services:
  api:
    build: 
        context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .env:/.env
  migrate:
    image: arigaio/atlas:latest
    environment:
      - DB_TOKEN=${DB_TOKEN}
    command: >
       schema apply
       --auto-approve
       --env dev
       --to file://schema.sql
       --dev-url "sqlite://dev?mode=memory"
    volumes:
      - ./schema.sql:/schema.sql
      - ./atlas.hcl:/atlas.hcl