services:
  api:
    build: 
        context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - .env:/.env
    depends_on:
      - db
  db: 
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=code-bookmarks